package cli

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"baton/internal/docker"
	"baton/internal/store"
	"baton/internal/supervisor"
)

// overrideMarker identifies a compose override file as baton's. baton will only
// rewrite a file carrying this line, so a hand-written override is never
// clobbered.
const overrideMarker = "# managed by baton — regenerated by `baton init`"

func runInit(arguments []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet("init", flag.ContinueOnError)
	flags.SetOutput(stderr)
	force := flags.Bool("force", false, "overwrite a compose override baton did not write")
	positionals, err := parseArguments(flags, arguments)
	if err != nil {
		return exitError
	}

	containerName := firstArgument(positionals)
	if containerName == "" {
		fmt.Fprintf(stderr, "baton: a container name is required\n")
		return exitError
	}

	container, err := docker.Inspect(containerName)
	if err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		return exitError
	}

	if err := installSupervisor(container.CodeRoot); err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		return exitError
	}
	fmt.Fprintf(stdout, "baton: installed the supervisor in %s\n",
		filepath.Join(container.CodeRoot, docker.ControlDir))

	if excluded, err := excludeFromGit(container.CodeRoot); err != nil {
		fmt.Fprintf(stderr, "baton: could not hide %s from git: %v\n", docker.ControlDir, err)
	} else if excluded {
		fmt.Fprintf(stdout, "baton: added %s/ to .git/info/exclude\n", docker.ControlDir)
	}

	stateStore, err := openStore()
	if err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		return exitError
	}
	var managed []managedContainer
	err = stateStore.Update(func(state *store.State) error {
		entry := state.Get(containerName)
		entry.Initialized = true
		entry.CodeRoot = container.CodeRoot
		for _, name := range state.Names() {
			if candidate := state.Get(name); candidate.Initialized {
				managed = append(managed, managedContainer{Name: name, CodeRoot: candidate.CodeRoot})
			}
		}
		return nil
	})
	if err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		return exitError
	}

	overridePath, err := findComposeOverride(container.CodeRoot)
	if err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		return exitError
	}
	written, err := writeComposeOverride(overridePath, managed, *force)
	if err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		fmt.Fprintf(stderr, "\nAdd this to %s by hand instead:\n\n%s\n", overridePath, overrideSnippet(managed))
		return exitError
	}
	if written {
		fmt.Fprintf(stdout, "baton: wrote %s\n", overridePath)
	}

	fmt.Fprintf(stdout, `
One restart is needed to pick up the supervisor. After that the container stays
up and baton moves the dev server between trees without bouncing it:

  PYENV_VERSION=localdev nc-docker up %s

Then check it took:

  baton status %s
`, containerName, containerName)
	return exitOK
}

type managedContainer struct {
	Name     string
	CodeRoot string
}

// installSupervisor drops the embedded script into the container's code root,
// where the bind mount makes it visible inside the container immediately.
func installSupervisor(codeRoot string) error {
	controlDir := filepath.Join(codeRoot, docker.ControlDir)
	if err := os.MkdirAll(controlDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", controlDir, err)
	}
	scriptPath := filepath.Join(controlDir, "supervisor.sh")
	if err := os.WriteFile(scriptPath, supervisor.Script, 0o755); err != nil {
		return fmt.Errorf("write %s: %w", scriptPath, err)
	}
	return nil
}

// excludeFromGit hides baton's control directory from git status. It uses
// .git/info/exclude rather than .gitignore so nothing lands in a commit — the
// same place the worktrees themselves are already excluded.
func excludeFromGit(codeRoot string) (bool, error) {
	excludePath := filepath.Join(codeRoot, ".git", "info", "exclude")
	existing, err := os.ReadFile(excludePath)
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	entry := docker.ControlDir + "/"
	for _, line := range strings.Split(string(existing), "\n") {
		if strings.TrimSpace(line) == entry {
			return false, nil
		}
	}

	if err := os.MkdirAll(filepath.Dir(excludePath), 0o755); err != nil {
		return false, err
	}
	file, err := os.OpenFile(excludePath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return false, err
	}
	defer file.Close()

	prefix := ""
	if len(existing) > 0 && !strings.HasSuffix(string(existing), "\n") {
		prefix = "\n"
	}
	if _, err := file.WriteString(prefix + entry + "\n"); err != nil {
		return false, err
	}
	return true, nil
}

// findComposeOverride locates the docker-compose.override.yml that sits beside
// the generated compose file, walking up from the code root to find it.
func findComposeOverride(codeRoot string) (string, error) {
	current := codeRoot
	for {
		if _, err := os.Stat(filepath.Join(current, "docker-compose.yml")); err == nil {
			return filepath.Join(current, "docker-compose.override.yml"), nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			return "", fmt.Errorf("no docker-compose.yml found above %s", codeRoot)
		}
		current = parent
	}
}

func writeComposeOverride(path string, managed []managedContainer, force bool) (bool, error) {
	existing, err := os.ReadFile(path)
	switch {
	case os.IsNotExist(err):
		// Nothing there, safe to write.
	case err != nil:
		return false, fmt.Errorf("read %s: %w", path, err)
	case !strings.Contains(string(existing), overrideMarker) && !force:
		return false, fmt.Errorf("%s already exists and baton did not write it", path)
	}

	if err := os.WriteFile(path, []byte(overrideSnippet(managed)), 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}

func overrideSnippet(managed []managedContainer) string {
	builder := &strings.Builder{}
	fmt.Fprintf(builder, "%s\n", overrideMarker)
	fmt.Fprintf(builder, "# Replaces each container's start command with baton's supervisor, which\n")
	fmt.Fprintf(builder, "# keeps the container up and moves the dev server between worktrees.\n")
	fmt.Fprintf(builder, "services:\n")
	for _, entry := range managed {
		fmt.Fprintf(builder, "  %s:\n", entry.Name)
		fmt.Fprintf(builder, "    command: /code/%s/supervisor.sh\n", docker.ControlDir)
	}
	return builder.String()
}
