package cli

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"baton/internal/docker"
	"baton/internal/store"
	"baton/internal/supervisor"
)

// overrideMarker identifies a compose override file as baton's. baton will only
// rewrite a file carrying this line, so a hand-written override is never
// clobbered.
const overrideMarker = "# managed by baton — regenerated by `baton init`"

func runInit(arguments []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet("init", flag.ContinueOnError)
	flags.SetOutput(stderr)
	force := flags.Bool("force", false, "overwrite a compose override baton did not write")
	dryRun := flags.Bool("dry-run", false, "show what would be written, change nothing")
	positionals, err := parseArguments(flags, arguments)
	if err != nil {
		return exitError
	}

	containerName := firstArgument(positionals)
	if containerName == "" {
		fmt.Fprintf(stderr, "baton: a container name is required\n")
		return exitError
	}

	container, err := docker.Inspect(containerName)
	if err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		return exitError
	}

	if *dryRun {
		return describeInit(container, stdout)
	}

	if err := installSupervisor(container.CodeRoot); err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		return exitError
	}
	fmt.Fprintf(stdout, "baton: installed the supervisor in %s\n",
		filepath.Join(container.CodeRoot, docker.ControlDir))

	stack := detectStack(container.CodeRoot)
	strategyPath, wrote, err := writeStrategy(container)
	if err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		return exitError
	}
	switch {
	case wrote:
		fmt.Fprintf(stdout, "baton: detected a %s repo", stack)
		if container.HealthPort != 0 {
			fmt.Fprintf(stdout, " on port %d%s", container.HealthPort, container.HealthPath)
		}
		fmt.Fprintf(stdout, "\nbaton: wrote a starter strategy at %s\n", strategyPath)
	default:
		fmt.Fprintf(stdout, "baton: kept the existing strategy at %s\n", strategyPath)
	}

	if stack == stackPip {
		fmt.Fprintf(stderr, "baton: python has no universal start command — fill in baton_start "+
			"in the strategy before taking the baton, or the container will not come up\n")
	}
	if stack == stackUnknown {
		fmt.Fprintf(stderr, "baton: no lockfile recognised, so there are no useful defaults — "+
			"fill in baton_prepare and baton_start in the strategy before taking the baton\n")
	}
	if hasMigrations(container.CodeRoot) {
		fmt.Fprintf(stdout, "baton: this repo has migrations and the database is shared between "+
			"worktrees; read the note in the strategy file before switching trees\n")
	}

	if excluded, err := excludeFromGit(container.CodeRoot); err != nil {
		fmt.Fprintf(stderr, "baton: could not hide %s from git: %v\n", docker.ControlDir, err)
	} else if excluded {
		fmt.Fprintf(stdout, "baton: added %s/ to .git/info/exclude\n", docker.ControlDir)
	}

	stateStore, err := openStore()
	if err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		return exitError
	}
	var managed []managedContainer
	err = stateStore.Update(func(state *store.State) error {
		entry := state.Get(containerName)
		entry.Initialized = true
		entry.CodeRoot = container.CodeRoot
		entry.CodeMount = container.CodeMount
		entry.Service = container.Service
		for _, name := range state.Names() {
			if candidate := state.Get(name); candidate.Initialized {
				mount := candidate.CodeMount
				if mount == "" {
					mount = "/code"
				}
				service := candidate.Service
				if service == "" {
					service = name
				}
				managed = append(managed, managedContainer{
					Name: name, Service: service, CodeRoot: candidate.CodeRoot, CodeMount: mount,
				})
			}
		}
		return nil
	})
	if err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		return exitError
	}

	overridePath, err := findComposeOverride(container.CodeRoot)
	if err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		return exitError
	}

	// Only containers belonging to this compose file go in this override.
	// Listing a container from another project would make compose read it as a
	// new service with no image and refuse the whole file.
	siblings := []managedContainer{}
	for _, candidate := range managed {
		if path, err := findComposeOverride(candidate.CodeRoot); err == nil && path == overridePath {
			siblings = append(siblings, candidate)
		}
	}
	written, err := writeComposeOverride(overridePath, siblings, *force)
	if err != nil {
		fmt.Fprintf(stderr, "baton: %v\n", err)
		fmt.Fprintf(stderr, "\nAdd this to %s by hand instead:\n\n%s\n", overridePath, overrideSnippet(siblings))
		return exitError
	}
	if written {
		fmt.Fprintf(stdout, "baton: wrote %s\n", overridePath)
	}

	fmt.Fprintf(stdout, `
One restart is needed to pick up the supervisor. After that the container stays
up and baton moves the app between trees without bouncing it. Recreate it the
way this project normally does — a plain compose setup is:

  docker compose up -d %s

Use your project's wrapper instead if it has one, since the container has to be
recreated rather than just restarted for the new command to apply.

Then check it took:

  baton status %s
`, container.Service, containerName)
	return exitOK
}

type managedContainer struct {
	Name      string
	Service   string
	CodeRoot  string
	CodeMount string
}

// installSupervisor drops the embedded script into the container's code root,
// where the bind mount makes it visible inside the container immediately.
func installSupervisor(codeRoot string) error {
	controlDir := filepath.Join(codeRoot, docker.ControlDir)
	if err := os.MkdirAll(controlDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", controlDir, err)
	}
	scriptPath := filepath.Join(controlDir, "supervisor.sh")
	if err := os.WriteFile(scriptPath, supervisor.Script, 0o755); err != nil {
		return fmt.Errorf("write %s: %w", scriptPath, err)
	}
	return nil
}

// excludeFromGit hides baton's control directory from git status. It uses
// .git/info/exclude rather than .gitignore so nothing lands in a commit — the
// same place the worktrees themselves are already excluded.
func excludeFromGit(codeRoot string) (bool, error) {
	excludePath := filepath.Join(codeRoot, ".git", "info", "exclude")
	existing, err := os.ReadFile(excludePath)
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	entry := docker.ControlDir + "/"
	for _, line := range strings.Split(string(existing), "\n") {
		if strings.TrimSpace(line) == entry {
			return false, nil
		}
	}

	if err := os.MkdirAll(filepath.Dir(excludePath), 0o755); err != nil {
		return false, err
	}
	file, err := os.OpenFile(excludePath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return false, err
	}
	defer file.Close()

	prefix := ""
	if len(existing) > 0 && !strings.HasSuffix(string(existing), "\n") {
		prefix = "\n"
	}
	if _, err := file.WriteString(prefix + entry + "\n"); err != nil {
		return false, err
	}
	return true, nil
}

// findComposeOverride locates the docker-compose.override.yml that sits beside
// the generated compose file, walking up from the code root to find it.
func findComposeOverride(codeRoot string) (string, error) {
	current := codeRoot
	for {
		if _, err := os.Stat(filepath.Join(current, "docker-compose.yml")); err == nil {
			return filepath.Join(current, "docker-compose.override.yml"), nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			return "", fmt.Errorf("no docker-compose.yml found above %s", codeRoot)
		}
		current = parent
	}
}

func writeComposeOverride(path string, managed []managedContainer, force bool) (bool, error) {
	existing, err := os.ReadFile(path)
	switch {
	case os.IsNotExist(err):
		// Nothing there, safe to write.
	case err != nil:
		return false, fmt.Errorf("read %s: %w", path, err)
	case !strings.Contains(string(existing), overrideMarker) && !force:
		return false, fmt.Errorf("%s already exists and baton did not write it", path)
	}

	if err := os.WriteFile(path, []byte(overrideSnippet(managed)), 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}

func overrideSnippet(managed []managedContainer) string {
	builder := &strings.Builder{}
	fmt.Fprintf(builder, "%s\n", overrideMarker)
	fmt.Fprintf(builder, "# Replaces each container's start command with baton's supervisor, which\n")
	fmt.Fprintf(builder, "# keeps the container up and moves the dev server between worktrees.\n")
	fmt.Fprintf(builder, "services:\n")
	for _, entry := range managed {
		fmt.Fprintf(builder, "  %s:\n", entry.Service)
		fmt.Fprintf(builder, "    command: %s/%s/supervisor.sh\n", entry.CodeMount, docker.ControlDir)
		fmt.Fprintf(builder, "    environment:\n")
		fmt.Fprintf(builder, "      - BATON_CODE=%s\n", entry.CodeMount)
		// Lets the supervisor make a worktree's .git pointer resolve, which is
		// what allows git-dependent tooling to run in worktrees at all.
		fmt.Fprintf(builder, "      - BATON_HOST_CODE=%s\n", entry.CodeRoot)
	}
	return builder.String()
}

// describeInit reports what init would do without touching anything. Useful for
// looking at an unfamiliar repo before committing to supervising it.
func describeInit(container *docker.Container, stdout io.Writer) int {
	stack := detectStack(container.CodeRoot)

	fmt.Fprintf(stdout, "container   %s\n", container.Name)
	fmt.Fprintf(stdout, "code root   %s\n", container.CodeRoot)
	fmt.Fprintf(stdout, "stack       %s\n", stack)
	if container.HealthPort != 0 {
		fmt.Fprintf(stdout, "health      port %d, path %s\n", container.HealthPort, container.HealthPath)
	} else {
		fmt.Fprintf(stdout, "health      not detected — set BATON_PORT in the strategy\n")
	}
	fmt.Fprintf(stdout, "migrations  %v\n", hasMigrations(container.CodeRoot))
	if len(container.Command) > 0 {
		fmt.Fprintf(stdout, "command     %s\n", strings.Join(container.Command, " "))
	}
	fmt.Fprintf(stdout, "\nwould write %s:\n\n", container.ControlPath("strategy.sh"))
	fmt.Fprint(stdout, strategyTemplate(stack, container))
	return exitOK
}

// runInstallSkill writes the embedded Claude Code skill to the user's skill
// directory.
//
// User level rather than project level on purpose. Claude Code keys memory and
// project settings to the working directory, so a session started in a git
// worktree gets a fresh, empty one and never sees anything written for the main
// clone. A user-level skill is the only placement that reaches every session
// wherever it starts, which is the whole point of documenting a tool sessions
// are supposed to use before they touch the container.
func runInstallSkill(arguments []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet("install-skill", flag.ContinueOnError)
	flags.SetOutput(stderr)
	dir := flags.String("dir", "", "where to install (default: ~/.claude/skills/baton)")
	force := flags.Bool("force", false, "overwrite an existing skill")
	if _, err := parseArguments(flags, arguments); err != nil {
		return exitError
	}

	target := *dir
	if target == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			fmt.Fprintf(stderr, "baton: cannot find your home directory: %v\n", err)
			return exitError
		}
		target = filepath.Join(home, ".claude", "skills", "baton")
	}

	path := filepath.Join(target, "SKILL.md")
	if _, err := os.Stat(path); err == nil && !*force {
		fmt.Fprintf(stderr, "baton: %s already exists; pass --force to replace it\n", path)
		return exitError
	}
	if err := os.MkdirAll(target, 0o755); err != nil {
		fmt.Fprintf(stderr, "baton: create %s: %v\n", target, err)
		return exitError
	}
	if err := os.WriteFile(path, supervisor.Skill, 0o644); err != nil {
		fmt.Fprintf(stderr, "baton: write %s: %v\n", path, err)
		return exitError
	}

	fmt.Fprintf(stdout, `baton: installed the skill at %s

Edit it to name the container this project shares, then start a new session —
skills are read at startup, so the one you are in now will not see it.
`, path)
	return exitOK
}
